{
 "title": "ASP.NET Core by Catalog Api",
 "description": "ASP.NET Core Custom Dashboard [Grafana ID 19924]",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Перцентили времени отклика запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Процент ошибок API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"catalog-api\", code=~\"4..|5..\"}[5m]) or vector(0)) / sum(rate(http_requests_received_total{job=\"catalog-api\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\", code=~\"4..\"}[5m]) or vector(0)) / sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\", code=~\"5..\"}[5m]) or vector(0)) / sum(rate(http_request_duration_seconds_bucket{job=\"catalog-api\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Общее количество HTTP-запросов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_requests_received_total{job=\"catalog-api\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"catalog-api\"} / 1024 / 1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Количество активных потоков",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_num_threads{job=\"catalog-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP запросы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(ceil(increase(http_requests_received_total{job=\"catalog-api\"}[15m])), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Активные HTTP-запросы",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=\"catalog-api\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Запросов в секунду (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"catalog-api\"}[1m]))",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Топ 10 запрашиваемыех эндпоинтов",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (method, code) (\r\n    increase(http_requests_received_total{job=\"catalog-api\"}[15m])\r\n  )\r\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Топ 10 HTTP методов",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "\r\ntopk(10,\r\n  sum by (method) (\r\n    increase(http_requests_received_total{job=\"catalog-api\"}[15m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}