# Собирает Docker-образ из указанного Dockerfile, 
# полностью игнорируя кэш, и присваивает ему тег promotion.grpc:latest
# docker build --platform=linux/amd64 --no-cache -t promotion.grpc:latest -f dockerfile-promotion .

# Выводит список всех сетей, созданных в Docker на вашем хосте
# docker network ls

# docker run -d \
#   --name promotion.grpc \
#   --network marketplace_default \
#   -p 7203:8080 \
#   -p 7213:8081 \
#   -e ConnectionStrings__MySqlConnection="..." \
#   -e ConnectionStrings__RedisConnection="..." \
#   -e MediatR__LicenseKey="..." \
#   promotion.grpc:latest

# docker run -d \
#   --name promotion.grpc \
#   --network marketplace_default \
#   -p 7203:8080 \
#   -p 7213:8081 \
#   promotion.grpc:latest

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["src/Services/Promotion/Promotion.Grpc/Promotion.Grpc.csproj", "src/Services/Promotion/Promotion.Grpc/"]
COPY ["src/Shared/Common.Kernel/Common.Kernel.csproj", "src/Shared/Common.Kernel/"]
COPY ["src/Shared/Common.Logging/Common.Logging.csproj", "src/Shared/Common.Logging/"]
COPY ["src/Shared/Common.Metrics/Common.Metrics.csproj", "src/Shared/Common.Metrics/"]

RUN dotnet restore "src/Services/Promotion/Promotion.Grpc/Promotion.Grpc.csproj"

COPY . .

RUN dotnet build "src/Services/Promotion/Promotion.Grpc/Promotion.Grpc.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "src/Services/Promotion/Promotion.Grpc/Promotion.Grpc.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Promotion.Grpc.dll"]
